### ISSUE TITLE
社群决定建在火信

### ISSUE THREAD

**Issue by LimLimOBC** [obetchain/obchain#32]
此前申请的QQ号，全部冻结，应该腾讯不支持境外号原因。
        综合大家意见，启动火信群。
        客服火信号12796230，填加进群。
       火信下载可自行搜索。

**Comment by LimLimOBC** [comment]
![-4fc49f2f80e57601](https://user-images.githubusercontent.com/89247505/130311496-02001489-9ef6-430a-970d-2638f68830b8.jpg)

**Comment by LimLimOBC** [comment]
![42ec8c39424b9a61](https://user-images.githubusercontent.com/89247505/130311665-4a0ba4d0-ee84-4e23-a494-0f1edc9a9c4b.jpg)
![1e58799198e2460a](https://user-images.githubusercontent.com/89247505/130311667-a863c004-54a6-4849-bc83-820ea3aaa5fd.jpg)
![-4fc49f2f80e57601](https://user-images.githubusercontent.com/89247505/130311669-172464cb-8999-4ff8-9ea2-6429f1c5ee3d.jpg)

**Comment by xiamen0612** [comment]
骗子你还是舔老欧JB去吧！欧大骗子的骗人智商你还没学到家。
